@END_POINT=http://localhost:3000/api/


# /api/reservations - get reservation list
curl --request GET \
  --url {{END_POINT}}reservations \
  --header 'Content-Type: application/json'
  --header 'cookie: authjs.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiYjZGd1lJMXpQN3hnby1QU3RzanRhdDZTRFBYaEp3dlE2TEJqSHFZNXI4NWxacUdTV2V6Tm5vTU5WMV81NVBBNjJhYVJ3VS1lNWxZS2xEQXhTbG9LZ1EifQ..ZeFyQGqBnKyYOl1ghRIgMw.NiRDZlZ2PV5m5Jhwvji0FbBNReHEvpd6EF4wGEvvVWr6NCzFjbosnLsT0eBrJ7ITCnNon-rClvWCL29LK0i47MqBR223iFwDIkoUSsC3z22bWdMDnOOLAiEzpSb9wnsH_qaQZrEawmulG9zrspvQQGNwVOuiRwhbkdbwvalz9eUUWoiwd7p8CEmduDm9GI_Q-iznSUGa4rJuSOHnelFhbs1msf4esHkjBldx5sHDFwE0T10MjNRuMvgMX9aJtL3I.E6Uyj3Rh3RB2j5LUv8AgFrXnBhIBRoV2sIvqmIGmo4I'
###


# /api/reservations/top - get latest 10 reservation list
curl --request GET \
  --url {{END_POINT}}reservations/top \
  --header 'Content-Type: application/json'
###

# Create New Reservation - /api/reservations/create
curl --request POST \
  --url {{END_POINT}}reservations/create \
  --header 'Content-Type: application/json'
  --data '{"roomNo":"A1002", "reservationStatus": "NEW", "checkInDate":"2025-01-01", "checkOutDate":"2025-01-31"}' 
###

# Update New Reservation - /api/reservations/create
curl --request PUT \
  --url {{END_POINT}}reservations/72603bd3-ded4-41f6-b887-3bcf664425d1/update \
  --header 'Content-Type: application/json'
  --data '{"id":"72603bd3-ded4-41f6-b887-3bcf664425d1","roomNo":"AAA", "checkInDate":"2025-01-01", "checkOutDate":"2025-01-31"}' 
###
