@END_POINT=http://localhost:3000/api/


# /api/reservations/top - get latest 10 reservation list
curl --request GET \
  --url {{END_POINT}}roomschedules \
  --header 'Content-Type: application/json'
###
