@END_POINT=http://localhost:3000/api/


# /api/reservations/top - get latest 10 reservation list
curl --request GET \
  --url {{END_POINT}}roomreservation?date=2025-07-01 \
  --header 'Content-Type: application/json'
###


# /api/reservations/top - get latest 10 reservation list
curl --request PATCH \
  --url {{END_POINT}}roomreservation?searchId=004a9491-6ab4-48ac-9a3c-0ef444c66864&searchRoomNo=A500 \
  --header 'Content-Type: application/json'
###
