UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A801' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A802' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='DOUBLE' WHERE `roomNo`='A803' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A804' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A805' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A806' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A807' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A808' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A809' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A810' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A811' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A812' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A813' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A814' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A815' AND `location`='MIDA';
UPDATE `room` SET `zone`='MODERN', `bedType`='SINGLE' WHERE `roomNo`='A816' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B141' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B151' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B152' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B511' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B512' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B521' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B522' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B531' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B532' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B541' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B542' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B551' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B552' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B441' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B442' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B241' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B242' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B431' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B432' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B421' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B422' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B411' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B412' AND `location`='MIDA';
UPDATE `room` SET `zone`='B', `bedType`='SINGLE' WHERE `roomNo`='B142' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A431' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A432' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A351' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A352' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='DOUBLE' WHERE `roomNo`='A141' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A142' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='DOUBLE' WHERE `roomNo`='A241' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='DOUBLE' WHERE `roomNo`='A242' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='DOUBLE' WHERE `roomNo`='A221' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A222' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A121' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A122' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A211' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A212' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A111' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A112' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A421' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='DOUBLE' WHERE `roomNo`='A422' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A411' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='DOUBLE' WHERE `roomNo`='A412' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='DOUBLE' WHERE `roomNo`='A311' AND `location`='MIDA';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A312' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='DOUBLE' WHERE `roomNo`='C271' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C261' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C262' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C251' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C252' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C241' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C242' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C231' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C232' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C141' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C142' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C131' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C132' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='DOUBLE' WHERE `roomNo`='C121' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='C122' AND `location`='MIDA';
UPDATE `room` SET `zone`='C', `bedType`='DOUBLE' WHERE `roomNo`='C281' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK101' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK102' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK103' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK104' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK105' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK106' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK107' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK108' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK109' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK110' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK111' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK112' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK113' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK114' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK115' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK116' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK201' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK202' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK203' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK204' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK205' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK206' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK207' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK208' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK209' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK210' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK211' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK212' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK213' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK214' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK215' AND `location`='MIDA';
UPDATE `room` SET `zone`='AK', `bedType`='SINGLE' WHERE `roomNo`='AK216' AND `location`='MIDA';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='101' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='102' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='103' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='104' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='105' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='106' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='107' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='108' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='109' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='110' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='111' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='112' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='113' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='114' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='115' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='116' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='117' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='118' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='119' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A1', `bedType`='SINGLE' WHERE `roomNo`='120' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='201' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='202' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='203' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='204' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='205' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='206' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='207' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='208' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='209' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='210' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='211' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='212' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='213' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='214' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='215' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='216' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='217' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='218' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='219' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A2', `bedType`='SINGLE' WHERE `roomNo`='220' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='301' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='302' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='303' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='304' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='305' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='306' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='307' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='308' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='309' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='310' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='311' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='312' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='313' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='314' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='315' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='316' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='317' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='318' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='319' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B1', `bedType`='SINGLE' WHERE `roomNo`='320' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='401' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='402' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='403' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='404' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='405' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='406' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='407' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='408' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='409' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='410' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='411' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='412' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='413' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='414' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='415' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='416' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='417' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='418' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='419' AND `location`= 'KKC';
UPDATE `room` SET `zone`='B2', `bedType`='SINGLE' WHERE `roomNo`='420' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='501' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='502' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='503' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='504' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='505' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='506' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='507' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='508' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='509' AND `location`= 'KKC';
UPDATE `room` SET `zone`='C', `bedType`='SINGLE' WHERE `roomNo`='510' AND `location`= 'KKC';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A101' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A102' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A103' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A104' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A105' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A106' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A107' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A108' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A109' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A110' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A111' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A112' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A113' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A114' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A115' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A116' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A117' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A118' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A119' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A120' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A121' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A122' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A123' AND `location`='HH';
UPDATE `room` SET `zone`='A', `bedType`='SINGLE' WHERE `roomNo`='A124' AND `location`='HH';
