export const queryObjectMapping = {
    date: 'date',
    searchArrivalDateTime: 'arrivalDateTime',
    searchCheckInDate: 'checkInDate',
    searchCheckInDateFrom: 'checkInDateFrom',
    searchCheckInDateUntil: 'checkInDateUntil',
    searchCheckOutDate: 'checkOutDate',
    searchCreatedDateFrom: 'createdDateFrom',
    searchCreatedDateUntil: 'createdDateUntil',
    searchDepartureDateTime: 'departureDateTime',
    searchDate: 'date',
    searchEmail: 'email',
    searchId: 'id',
    searchName: 'name',
    searchNationalId: 'nationalId',
    searchPassport: 'passport',
    searchPhone: 'phone',
    searchPrepaidPackage: 'prepaidPackage',
    searchPromotionPackage: 'promotionPackage',
    searchRemark: 'remark',
    searchReservationStatus: 'reservationStatus',
    searchReservationType: 'reservationType',
    searchUserName: 'userName',
}